### ISSUE TITLE
medial dorsal thalamic nucleus vs medial dorsal thalamic nucleus

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mouse-anatomy-ontology#10]
I realize spatial qualifiers can be deceptive the nervous system... but should these two classes not be merged?

![mdtn](https://cloud.githubusercontent.com/assets/50745/6883152/545b29f4-d55d-11e4-897a-6b1270671bd0.png)

**Comment by tfhayamizu** [comment]
I believe other groups have made a case for having both terms.
For example:
![screen shot 2015-04-13 at 1 12 46 pm](https://cloud.githubusercontent.com/assets/913577/7121103/00f97c04-e1e0-11e4-9d83-52362b64b94c.png)
I have moved "medial dorsal thalamic nucleus" (EMAPA:35544) to 
be part-of ""dorsal thalamus medial thalamic group" (EMAPA:35296)
