### ISSUE TITLE
temporal range of germ layer

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mouse-anatomy-ontology#118]
We have a GO annotation to:

    cytoplasm AND part_of some testis AND part_of some 'germ layer'

I am trying to figure out what this means and why someone would annotate to this

It looks like it's unsatisfiable due to conflicting temporal ranges:

 * left/right testis starts at TS28 in EMAPA
 * germ layer ends at TS26

But I am wondering if even TS26 is extending it too far, surely the germ layers end before this?

cc @ukemi @vanaukenk

**Comment by tfhayamizu** [comment]
RE: "surely the germ layers end before this?"

The EMAPA includes 'extraembryonic' endoderm, ectoderm and mesoderm as subclasses of germ layer. While this classification may be debatable, extraembryonic mesoderm, at least, is thought to arise during gastrulation. (See, e.g., https://onlinelibrary.wiley.com/doi/full/10.1111/dgd.12294.) 

The EMAPA has terms for amnion ectoderm and yolk sac endoderm (with annotations) extending to TS26. Not saying these are necessarily correct, but they support the stage range for 'germ layer.'

**Comment by cmungall** [comment]
OK, and I heard from @ukemi that the curator actually intended to use 'germinal epithelium' rather than germ layer!
