### ISSUE TITLE
claws vs nails

### ISSUE THREAD

**Issue by cmungall** [obophenotype/mouse-anatomy-ontology#9]
EMAPA has a 'nail' that is unrelated to the serially repeated 'claw's:

![claw](https://cloud.githubusercontent.com/assets/50745/6883002/2ebd1c52-d558-11e4-8d41-3e00574a9d3e.png)

**Comment by cmungall** [comment]
also note the grouping for manual claw is not repeated on the foot

**Comment by tfhayamizu** [comment]
Issue noted and will be rectified. The claw/nail discrepancy again from the legacy EMAP ontology, where Kaufman used "claw" label for the 1992 mouse Atlas, while much of MA terminology came from anatomy and pathology references for adult mice. Overall, "nail" appears to be most used, with Kaufman and Bard using both terms for their 1999 book, as well as all pathology references I have found. Interesting discussion of this issue in: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3579226/
It may be awhile until I can clean up all of the nomenclature, but I will revise the relationships, and add a term for "hindlimb nail".

**Comment by cmungall** [comment]
Thanks for the link!
